### ISSUE TITLE
State Probability matrix 

### ISSUE THREAD

**Issue by adpsu** [mortamini/hhsmm#1]
Hello,

Is there any way we can retrieve the state probability matrix of three different states (3xn) for input data X (1xn) for hsmm?

**Comment by mortamini** [comment]
Hi
If I am not wrong,  you need to estimate a non-homogeneus HHSMM whose transition probability matrix is different for each time. I have provided the codes in R but it is too slow and I have not yet translated them into C++ to be faster. Besides,  I have not developed codes for prediction and simulation of such models. Thus, I am not yet ready to publish them in a new version. I hope I can consider them in future.

**Comment by adpsu** [comment]
Thank you for your reply. I was wondering if you have any documentation of all the output variables? Could not find all the details from the pdf available in the cran documentation. I am specifically interested in estep variables (especially the gamma).

Thank you.

**Comment by mortamini** [comment]
You can read more about the hhsmm package in the following paper: 

https://link.springer.com/article/10.1007/s00180-022-01248-x

which is also available on arxiv
