### ISSUE TITLE
AR HMM

### ISSUE THREAD

**Issue by senguptaagni** [mortamini/hhsmm#2]
I am trying to create a autoregressive HMM model with lag >1 (say. lag=2). I am first using 'lagdata' function with argument 'data' and lag = 2 to generate the lagged data (train2). The following code is giving error:

clus = initial_cluster(train = train2 , nstate=3 , nmix = 1,
                       ltr = FALSE , final.absorb = FALSE , verbose = TRUE, regress = TRUE,
                       resp.ind =1)

initmodel = initialize_model(clus = clus , mstep = mixlm_mstep,
                             dens.emis = dmixlm, sojourn = NULL, semi = rep(FALSE,3),
                             M = max(train2$N), verbose=TRUE, resp.ind = 1)

regime_fit = hhsmmfit(x = train2, model = initmodel , mstep = mixlm_mstep, resp.ind = 1,
                      M = max(train2$N), par = list(verbose = FALSE))
" Error in x %*% t(model$parms.emission$coefficients[[j]]) : 
  non-conformable arguments"

-- Can you please help me find what's wrong. This code is running for lag =1,  but shows error for any lag > 1.

**Comment by mortamini** [comment]
Thank you very much for your feedback. I will check the problem and reply you as soon as possible.

**Comment by mortamini** [comment]
The bug has been resolved. The corrected version 0.3.3 will be published after Aug. 5, on CRAN (for now, there is no submission on CRAN due to the vacations).

**Comment by senguptaagni** [comment]
Sounds good, Dr. Amini. Thank you for this very helpful package.

**Comment by mortamini** [comment]
The corrected version 0.3.3 is now on CRAN: https://cran.r-project.org/package=hhsmm

**Comment by senguptaagni** [comment]
Thank you Dr. Amini.
