### ISSUE TITLE
Multinomial emission distribution

### ISSUE THREAD

**Issue by rtrepos** [mortamini/hhsmm#3]
Hello,
First, I would like to thank you for this work,
I wanted to use your package in order to infer hsmm with a custom emission distribution which is a multinomial distribution (kind of non parametric distribution on discrete values). Do you think I can achieve this ?
Best
Ronan

**Comment by mortamini** [comment]
Dear Ronan

Thanks for your comment. Actually, you can add any user-defined emission distribution and use it in your code. For the multinomial (with a number of experiments equal to 1) emission distribution you need to define three functions as follows (Maybe you want to edit them):


mstep.multinomial <- function (x, wt){                 # this is the mstep function you need to use 
	k = ncol(wt)
	prob = numeric(k)
	n = max(x)                  # this is dangerous work since the max level might be unavailable in the data
                                           # you might prefer to add a control argument with the correct number of levels to this function
	y = t(sapply(1:n, function(i) 1*(x == I)))          #your data must be like x = c(1,1,2,1,3,2,1,...)
	for (i in 1:k) prob[i]=sapply(1:n, function(j) weighted.mean(y[j,],wt[,i]))
	list(prob = prob)
}

dmultinomial.hhsmm <- function (x, j, model){           # this is the emission mass function you need to use 
	y = t(sapply(1:n, function(i) 1*(x == I)))     #your data must be like x = c(1,1,2,1,3,2,1,...)
	dmultinom(y, 1, model$parms.emission$prob[j])
}

rmultinomial.hhsmm <- function (j, model){               # this function can be used in simulation in simulate function
	n = length(model$parms.emission$prob[j])
	(1:n) %*% rmultinom(1, 1, model$parms.emission$prob[j])   #the output will be like x = c(1,1,2,1,3,2,1,...)
}

I will add these functions in the new version of the hhsmm package in the future.

**Comment by rtrepos** [comment]
Thanks a lot, I was indeed trying to do this. 
I tested your code with the following  call without success  yet :

```
set.seed(1012)
nparam_emission_mat = rbind(c(0.6,  0.2, 0.2),
                            c(0.2, 0.6,  0.2),
                            c(0.2, 0.2, 0.6))
nparam_model = hhsmmspec(
  init=c(1,0,0),
  transition=rbind(c(0, 0.9, 0.1),
                   c(0.1, 0, 0.9),
                   c(0.9, 0.1, 0)),
  parms.emission = list(prob=nparam_emission_mat),
  sojourn = list(lambda=rep(3, 3),
                 shift=rep(1, 3),
                 type="poisson"),
  dens.emission= dmultinomial.hhsmm,
  remission = rmultinomial.hhsmm,
  mstep = mstep.multinomial,
  semi = rep(TRUE, 3))
ss = simulate(nparam_model, remission = rmultinomial.hhsmm,  nsim=10)
plot(ss$x); lines(ss$s)
nparam_model_init = nparam_model
resfit = hhsmmfit(x=ss$x, model=nparam_model_init, M=30, 
                  par=list(lock.transition=T, lock.d=T))
```

I had to modify the function to simulate by condidering that I have a matrix in model$parms.emission$prob, ie:

```
rmultinomial.hhsmm <- function (j, model){ # this function can be used in simulation in simulate function
  n = length(model$parms.emission$prob[j,])
  (1:n) %*% rmultinom(1, 1, model$parms.emission$prob[j,]) #the output will be like x = c(1,1,2,1,3,2,1,...)
}
```

Then I add an error in the density function during the estimation.
In the density function, n and I are unknown. As you suggested n should be provided in the control list (in my case this is 3, as the number of hidden state). But what is I ? Is this the number of possible hidden state, ie model$J ?

Thks again!

**Comment by mortamini** [comment]
Dear Ronan

Here is what you need:

library(hhsmm)

mstep.multinomial <- function (x, wt, n){ 
	k = ncol(wt)
	prob = list()
	for(i in 1:k) prob[[i]] = numeric(n)
	y = t(sapply(1:n, function(i) 1*(x == i))) 
	for (i in 1:k) prob[[i]]=sapply(1:n, function(j) weighted.mean(y[j,],wt[,i]))
	list(prob = prob)
}

dmultinomial.hhsmm <- function (x, j, model, n){ 
	y = t(sapply(1:n, function(i) 1*(x == i))) 
	sapply(1:ncol(y), function(i) dmultinom(y[,i], 1, model$parms.emission$prob[[j]]))
}

rmultinomial.hhsmm <- function (j, model){ 
  	n = length(model$parms.emission$prob[[j]])
  	(1:n) %*% rmultinom(1, 1, model$parms.emission$prob[[j]]) 
}

set.seed(1012)
nparam_emission = list(c(0.6,  0.2, 0.2),
                            c(0.2, 0.6,  0.2),
                            c(0.2, 0.2, 0.6))
nparam_model = hhsmmspec(
  init=c(1,0,0),
  transition=rbind(c(0, 0.9, 0.1),
                   c(0.1, 0, 0.9),
                   c(0.9, 0.1, 0)),
  parms.emission = list(prob = nparam_emission), 
  sojourn = list(lambda=rep(3, 3),
                 shift=rep(1, 3),
                 type="poisson"),
  dens.emission= dmultinomial.hhsmm,
  remission = rmultinomial.hhsmm,
  mstep = mstep.multinomial,
  semi = rep(TRUE, 3))
ss = simulate(nparam_model, remission = rmultinomial.hhsmm,  nsim=10)
plot(ss)
nparam_model_init = nparam_model
resfit = hhsmmfit(x=ss, model=nparam_model_init, mstep = mstep.multinomial, 
n = 3, M = 30, par=list(lock.transition=T, lock.d=T))
resfit$model

**Comment by rtrepos** [comment]
Thank you ! It works well.
I can now close this issue
