### ISSUE TITLE
How are computed the gamma values of Explicit duration HSMM ?

### ISSUE THREAD

**Issue by rtrepos** [mortamini/hhsmm#5]
Hi again Morteza,

I was looking how are computed your gamma values of HSMM.
I am talking of those that are used on the following line to compute the smoothing precition of hsm states.
https://github.com/mortamini/hhsmm/blob/9b1989404ca8b1d7f60fc01f0e6e2145c61685b5/R/predict-hhsmm.R#L220

On the C code, I can see that a structure for the gamma values is given as input, but it is never filled (I think).

Thanks again
Best
Ronan

**Comment by mortamini** [comment]
Hi Ronan

gamma is copied from L0 values in C code as follows:

memcpy(gamma+j*ln,L0[j],ln*sizeof(double));

see

https://github.com/mortamini/hhsmm/blob/main/src-i386/hhsmm.c

and you can see also

https://www.geeksforgeeks.org/memcpy-in-cc/

**Comment by rtrepos** [comment]
Ok I finally found them. Thank you for your help.
