### ISSUE TITLE
How to model categorical/discrete emissions?

### ISSUE THREAD

**Issue by neoyinzhanghan** [mortamini/hhsmm#6]
Hi! I am trying to model polymer sequences. The observed sequence should take values 1,2,3 or 4. 
```
num_states <- 3
semi <- rep(TRUE, num_states)
init_probs <- rep(1/num_states, num_states)

transition_matrix <- matrix(1/(num_states-1), nrow = num_states, ncol = num_states)

for (i in seq_along(semi_vector)) {
  if (semi_vector[i]) {
    transition_matrix[i, i] <- 0
  }
}
parms_emission <- list(mu = rep(0, num_states), sigma = rep(1, num_states))

sojourn <- list(shape = c(0, 3, 0), scale = c(0, 10, 0), type = "gamma")
dens_emission <- dmixmvnorm

initmodel <- hhsmmspec(
  init = init_probs,
  transition = transition_matrix,
  parms.emission = parms_emission,
  sojourn = sojourn,
  dens.emission = dens_emission,
  remission = rmixmvnorm, # Ensure this function is correctly defined for your model
  mstep = mixmvnorm_mstep, # Ensure this function is correctly defined for your model
  semi = semi
)

fit1 <- hhsmmfit(x = prepared_data, model=initmodel, M=max(prepared_data$N))
```

`prepared_data` is the output of function `hhsmmdata`. When I run this my terminal is spammed with `Warning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: NaNs producedWarning: ...`

I am assuming that this has something to do with the emission distribution, hence leading to this inquiry. 
I am new to HHSMM, so not familiar with all the deep details of the architecture. Would appreciate any help and guidance.

**Comment by mortamini** [comment]
Hi

For categorical data type (1,2,3,4) you have to use 

1 - dmultinomial.hhsmm (pdf of the multinomial emission distribution for hhsmm) as the emisson distribution (not dmixmvnorm)

2 - parms_emission which should be par <- list(prob = ... ) and not list(mu = .., sigma = ...), 

3- remission should be rmultinomial.hhsmm and not rmixmvnorm

4- mstep =  mstep.multinomial  and not mixmvnorm_mstep

Good luck

**Comment by neoyinzhanghan** [comment]
Thank you so much for the thorough response! 
I am able to modify the code and see what is going on (see below).
One more thing, I run into a bug which I think should be straightforward to solve but I couldn't figure it out.

```
# Define the number of states based on your data
num_states <- 3

semi_vector = c(TRUE, TRUE, TRUE)

# Semi-Markov states (assuming all states are semi-Markovian for the example)
semi <- rep(TRUE, num_states)

# Initial probabilities (assuming uniform distribution for the example)
init_probs <- rep(1/num_states, num_states)

# Transition matrix (assuming equal probability for transitions for the example)
transition_matrix <- matrix(1/(num_states-1), nrow = num_states, ncol = num_states)

# Adjust the transition matrix for semi-Markov states
# This sets the diagonal to 0 for semi-Markov states
for (i in seq_along(semi_vector)) {
  if (semi_vector[i]) {
    transition_matrix[i, i] <- 0
  }
}
# Emission parameters
# Assuming Gaussian emissions, you'd need a mean and sd for each state
# Replace with actual parameters based on your data
parms_emission <- list(prob = list(c(0.6, 0.2, 0.1, 0.1), c(0.2, 0.6, 0.1, 0.1), c(0.5, 0.3, 0.1, 0.1)))

# Sojourn distribution (choose and specify the correct one for your model)
# Here's an example using a negative binomial sojourn distribution
sojourn <- list(shape = c(1, 3, 1), scale = c(3, 10, 4), type = "gamma")

# Define emission distribution function for a mixture of Gaussian emissions
dens_emission <- dmultinomial.hhsmm

# Proceed with model initialization and fitting
initmodel <- hhsmmspec(
  init = init_probs,
  transition = transition_matrix,
  parms.emission = parms_emission,
  sojourn = sojourn,
  dens.emission = dens_emission,
  remission = rmultinomial.hhsmm, # Ensure this function is correctly defined for your model
  mstep = mstep.multinomial, # Ensure this function is correctly defined for your model
  semi = semi
)


# debug(hhsmmfit)
fit1 <- hhsmmfit(x = prepared_data, model=initmodel, M=max(prepared_data$N))
```

I changed the code to the above, but now I run into this error:

```
Error in lapply(X = X, FUN = FUN, ...) : 
argument "n" is missing, with no default
8. lapply(X = X, FUN = FUN, ...)
7. sapply(1:n, function(i) 1 * (x == i))
6. t(sapply(1:n, function(i) 1 * (x == i)))
5. f(x, state, new.model, ...)
4. FUN(X[[i]], ...)
3. lapply(X = X, FUN = FUN, ...)
2. sapply(1:J, function(state) f(x, state, new.model, ...))
1. hhsmmfit(x = prepared_data, model = initmodel, M = max(prepared_data$N))
```

I am not sure how to debug this. Any help or point would be really appreciated.

**Comment by mortamini** [comment]
Hi 
Please read the manual of the package carefully
The dmultinomial.hhsmm has an additional argument n which should be passed to hhsmmfit function through ... 
so you have to execute the following code
fit1 <- hhsmmfit(x = prepared_data, model=initmodel, n=4, M=max(prepared_data$N))

**Comment by neoyinzhanghan** [comment]
Oh you are right! Apologies for the oversight and thank you for your help that fixed the problem!

**Comment by neoyinzhanghan** [comment]
@mortamini 

Sorry to bother you again. The model trained perfectly. My next goal is to use the `score` function to compute the likelihood of a set of data against the trained model. 

I read in the manual that the `score` function takes in two arguments `xnew` and `fit`. The former is the new data and the fit is the fitted model, with no other arguments.

However, when I run:
``` 
score(xnew=prepared_data, fit=fit1)
```

I get the same argument `n` missing error, despite the fact that the model has been trained successfully:

```
Error in lapply(X = X, FUN = FUN, ...) : 
argument "n" is missing, with no default
11. lapply(X = X, FUN = FUN, ...)
10. sapply(1:n, function(i) 1 * (x == i))
9. t(sapply(1:n, function(i) 1 * (x == i)))
8. f(x, state, new.model, ...)
7. FUN(X[[i]], ...)
6. lapply(X = X, FUN = FUN, ...)
5. sapply(1:J, function(state) f(x, state, new.model, ...))
4. hhsmmfit(xx, fit$model, fit$mstep, M = fit$M, par = list(maxit = 1, 
verbose = FALSE))
3. withCallingHandlers(expr, warning = function(w) if (inherits(w, 
classes)) tryInvokeRestart("muffleWarning"))
2. suppressWarnings(score <- c(score, hhsmmfit(xx, fit$model, fit$mstep, 
M = fit$M, par = list(maxit = 1, verbose = FALSE))$loglik))
1. score(xnew = prepared_data, fit = fit1)
```

Would appreciate any points on what I could be doing wrong. Thank you in advance for your help!

**Comment by mortamini** [comment]
You are right!
This is a Bug of the package that the score() function is not well-defined for passing the arguments of the dens.emisson into hhsmmfit() function!
Thanks for your report.
I will resolve this issue in a new version of the hhsmm package.
Meanwhile, you can redefine the score function as follows, so that you can do your job:

score <- function (xnew, fit, ...) 
{
    if (mode(xnew) == "numeric" | mode(xnew) == "integer") {
        if (is.null(dim(xnew))) {
            N = nrow(xnew <- t(as.matrix(xnew)))
        }
        else {
            N = nrow(xnew <- as.matrix(xnew))
        }
    }
    else {
        N = xnew$N
        xnew = as.matrix(xnew$x)
    }
    Nc = c(0, cumsum(N))
    score = c()
    for (i in 1:length(N)) {
        for (j in (Nc[i] + 1):(Nc[i + 1])) {
            xx = matrix(xnew[j, ], 1, ncol(xnew))
            suppressWarnings(score <- c(score, hhsmmfit(xx, fit$model, 
                fit$mstep, ..., M = fit$M, par = list(maxit = 1, verbose = FALSE))$loglik))
        }
    }
    score
}

and use it for your case as follows:

score(xnew = prepared_data, fit = fit1, n=4)

**Comment by neoyinzhanghan** [comment]
Thank you for your help! Glad I could be of help catching a bug.
The code you provided seems to lead to a further error. (I renamed the function to `score_debugged`.)

```
> score_debugged(xnew = new_prepared_data, fit = fit1, n=4)
Error in dmultinom(y[, i], 1, model$parms.emission$prob[[j]]) : 
  x[] and prob[] must be equal length vectors.
Called from: dmultinom(y[, i], 1, model$parms.emission$prob[[j]])
```

This is the function I called based on yours:
```
score_debugged <- function (xnew, fit, ...)
{
  if (mode(xnew) == "numeric" | mode(xnew) == "integer") {
    if (is.null(dim(xnew))) {
      N = nrow(xnew <- t(as.matrix(xnew)))
    }
    else {
      N = nrow(xnew <- as.matrix(xnew))
    }
  }
  else {
    N = xnew$N
    xnew = as.matrix(xnew$x)
  }
  Nc = c(0, cumsum(N))
  score = c()
  for (i in 1:length(N)) {
    for (j in (Nc[i] + 1):(Nc[i + 1])) {
      xx = matrix(xnew[j, ], 1, ncol(xnew))
      suppressWarnings(score <- c(score, hhsmmfit(xx, fit$model,
                                                  fit$mstep, ..., M = fit$M, par = list(maxit = 1, verbose = FALSE))$loglik))
    }
  }
  return(score)
}

# compute the log likelihood 
score_debugged(xnew = prepared_data, fit = fit1, n=4)
```

**Comment by mortamini** [comment]
Thanks again Neo.
It was a serious BUG! 
The correct code is as follows:


score_debugged <- function (xnew, fit, ...)
{
  if (mode(xnew) == "numeric" | mode(xnew) == "integer") {
    if (is.null(dim(xnew))) {
      N = nrow(xnew <- t(as.matrix(xnew)))
    }
    else {
      N = nrow(xnew <- as.matrix(xnew))
    }
  }
  else {
    N = xnew$N
    xnew = as.matrix(xnew$x)
  }
  Nc = c(0, cumsum(N))
  score = c()
  for (i in 1:length(N)) {
      xx = matrix(xnew[(Nc[i] + 1):(Nc[i + 1]), ], (Nc[i + 1])-(Nc[i] + 1)+1, ncol(xnew))
      suppressWarnings(score <- c(score, hhsmmfit(xx, fit$model,
                                                  fit$mstep, ..., M = fit$M, par = list(maxit = 1, verbose = FALSE))$loglik))
  }
  return(score)
}

# compute the log likelihood 
score_debugged(xnew = prepared_data, fit = fit1, n=4)

I will fix this issue in the next version of the hhsmm package

**Comment by neoyinzhanghan** [comment]
Thank you Morteza! This works and is very helpful. Really appreciate all your patient support.
