### ISSUE TITLE
sojourn = NULL

### ISSUE THREAD

**Issue by neoyinzhanghan** [mortamini/hhsmm#7]
Hi Morteza,

I have a question about the sojourn distribution specification supported by the package. 
I am hoping to fit a model without specifying a sojourn distribution. My understanding is that in that case, theoretically the sojourn time coupled with the state can be considered a state in itself, and the hsmm updates like a hmm with this coupled state.

I see some usage examples in your documentation where `sojourn = NULL` in the model initialization.
```
initmodel = initialize_model(clus = clus, mstep = mixlm_mstep,
dens.emission = dmixlm, sojourn = NULL, semi = rep(FALSE, 3),
M = max(train$N),verbose = TRUE)
```

Does this correspond to the behaviour I described?

Also the `sojourn = NULL` seems to be bugged.

When I run
```
train_hsmm_clus <- function(prepared_data, M=9) {
  clus = initial_cluster(train = prepared_data, nstate = 3, nmix = NULL, ltr = FALSE, final.absorb = FALSE, verbose = TRUE)
  initmodel = initialize_model(clus = clus, mstep = mstep.multinomial, n = 4, dens.emission = dmultinomial.hhsmm, sojourn = NULL, semi = rep(TRUE, 3), M = M,verbose = TRUE)
  fit1 = hhsmmfit(x = prepared_data, model = initmodel, mstep = mstep.multinomial, n = 4, M = M)

  return(fit1)
}
```

I will get the error:
```
Within sequence clustering ... 
Intitial estimation .... 
State  1  estimation 
State  2  estimation 
State  3  estimation 
Initializing model ... 
Error in if (sojourn == "auto") { : argument is of length zero
```

However, the model training runs just fine if I replace `sojourn = NULL` with `sojourn = "auto"`.

Any help would be really appreciated.

**Comment by mortamini** [comment]
Hi Neo

sojourn = NULL is only for the HMM model where semi = rep(FALSE, nstate). When you set any TRUE value in semi vector, sojourn can not be NULL, instead it can be set to "auto" for automatic sojourn selection.

**Comment by neoyinzhanghan** [comment]
Hi Morteza,

Thanks a lot for the clarification. Just a further question.
How is the sojourn automatically selected under auto?
Would appreciate if you could provide a pointer to the right resource.
Thank you!

Best regards
Neo

**Comment by mortamini** [comment]
Dear Neo

The auto sojourn selection process is as follows:

1- An initial clustering is done using initial.cluster function (using kmeans for continuous data) 
2- The sojourn times are evaluated based on initial clustering 
3- The chi-square test is performed for a list of candidate sojourn distributions and the best fitted one is selected.

Since for multinomial categorical data (your case) the initial clustering is not efficient, I do not recommend you to use the "auto" option for the sojourn argument.

**Comment by neoyinzhanghan** [comment]
Thank you Morteza! This clarified and everything worked. Appreciate all your patient support!
