### ISSUE TITLE
Predict function is bugged

### ISSUE THREAD

**Issue by neoyinzhanghan** [mortamini/hhsmm#8]
Hi Morteza,

I believe that the `predict` function in your package is bugged much like post #6.

This is how I trained my model:
``` 

train_hsmm_clus <- function(prepared_data, sojourn="auto", M=9) {
  clus = initial_cluster(train = prepared_data, nstate = 3, nmix = NULL, ltr = FALSE, final.absorb = FALSE, verbose = TRUE)
  initmodel = initialize_model(clus = clus, mstep = mstep.multinomial, n = 4, dens.emission = dmultinomial.hhsmm, sojourn = sojourn, semi = rep(TRUE, 3), M = M,verbose = TRUE)
  fit1 = hhsmmfit(x = prepared_data, model = initmodel, mstep = mstep.multinomial, n = 4, M = M)
  
  return(fit1)
}
```

I am trying to get the model prediction by calling, (the data here is exactly the data on which the model is trained),
``` results <- predict(fit, prepared_data) ```

This results in an error: (this error seems analogous to the one in post #6
```Error in lapply(X = X, FUN = FUN, ...) : 
  argument "n" is missing, with no default
```

n does not seem to be a parameter of the predict function.

Any pointer would be greatly appreciated!

Neo

**Comment by mortamini** [comment]
Dear Neo

In the Manual you see

predict(
object,
newdata,
future = 0,
method = "viterbi",
RUL.estimate = FALSE,
confidence = "max",
conf.level = 0.95,
...
)
that 
... additional parameters for the dens.emission and mstep functions
so you have to consider n in place of ...

**Comment by neoyinzhanghan** [comment]
Hi Morteza,

Thank you for your response, I forgot to mention that I also tried
`results <- predict(fit, prepared_tao_data, n=4)` and the same error arises (with an additional warning message)

```
Error in lapply(X = X, FUN = FUN, ...) : 
  argument "n" is missing, with no default
In addition: Warning message:
In predict.hhsmm(fit, prepared_tao_data, n = 4) :
  x is a primitive vector.  Assuming single sequence.
```

Thank you

Neo

**Comment by mortamini** [comment]
You are right that this is more or less a bug! Because the place of ... in the predict function should be moved to the third place (I will resolve it in a forthcoming version). For now, you have to use it as follows:

predict(fit, prepared_tao_data, future = 0, method = "viterbi", RUL.estimate = FALSE, 
confidence = "max", conf.level = 0.95, n=4)

**Comment by neoyinzhanghan** [comment]
Hi Morteza,

Thank you so much for providing the fix. Unfortunately, I will ran into issues when trying to use this code.
I think it might be helpful for me to share a model checkpoint and minimal data example with you that can be used to reproduce this error.

The error is the following:

```
> predict(fit, prepared_tao_data, future = 0, method = "viterbi", RUL.estimate = FALSE,
+         confidence = "max", conf.level = 0.95, n=4)
Error in 1:n : NA/NaN argument
In addition: Warning messages:
1: In predict.hhsmm(fit, prepared_tao_data, future = 0, method = "viterbi",  :
  x is a primitive vector.  Assuming single sequence.
2: In 1:n : numerical expression has 2 elements: only the first used
```

And the code I was using is:

```
model_path <- "/Users/neo/Downloads/Tao/models/35:35_gamma_1.rda"
data_path <- "/Users/neo/Downloads/Tao/output_35:35.csv"

prepare_data_all_tao <- function(data) {
  # Convert all columns to numeric, assuming each column represents a sequence element
  # Any non-numeric strings will result in NA values
  data <- data.frame(lapply(data, function(x) as.numeric(as.character(x))))
  
  # Handle NA values if necessary, e.g., replace with zeros or remove rows/columns containing NAs
  # This step depends on the specific requirements and handling of missing data
  data[is.na(data)] <- 0  # Example: replacing NA with 0
  
  # Flatten the data frame into a single vector of digits
  concatenated_digits <- as.numeric(unlist(data))
  
  # Get the length of sequences (number of columns)
  sequence_lengths <- rep(ncol(data), nrow(data))
  
  # Create a list of digits and their lengths
  data_list <- list("Digits" = concatenated_digits, "Lengths" = sequence_lengths)
  
  # Preparing X as a matrix where each row corresponds to a digit
  X_matrix <- matrix(data_list$Digits, nrow = length(data_list$Digits), ncol = 1, byrow = TRUE)
  
  # Using the 'hhsmmdata' function
  prepared_data = hhsmmdata(X_matrix, data_list$Lengths)
  
  return(prepared_data)
}

tao_data <- read.csv(data_path)
prepared_tao_data <- prepare_data_all_tao(tao_data)

predict(fit, prepared_tao_data, future = 0, method = "viterbi", RUL.estimate = FALSE,
        confidence = "max", conf.level = 0.95, n=4)
```

Here is a [Google Drive Link](https://drive.google.com/file/d/13PO5JmggKSbDfAnRrZOSU3duyIcBTOe_/view?usp=sharing
) to the model file and data csv file. I thought it might be helpful for me to provide you more context.

Thank you as always for your help on this package.

Best regards
Neo

**Comment by mortamini** [comment]
The only point about using ... in R is that you must use all arguments by their names, then you can use the predict function as follows:


predict(object = fit, newdata=prepared_data_test, n=4)

**Comment by neoyinzhanghan** [comment]
Just tried it out and this worked! Thank you so much Morteza!
